language: objective-c
before_install:
  - brew update
  - brew tap homebrew/dupes
  - brew tap homebrew/versions
install:
  - mkdir -p $(brew --repo)/Library/Taps
  - ln -s $PWD $(brew --repo)/Library/Taps/homebrew-hhvm
  - brew tap --repair
env:
  - PACKAGE=folly
  - PACKAGE=jemallocfb
  - PACKAGE=libdwarf
  - PACKAGE=libeventfb
  - PACKAGE=hhvm
script:
  - brew audit $PACKAGE
  - brew install -v $PACKAGE
  - '! brew cat $PACKAGE | grep -q "test do" || brew test -v $PACKAGE'
matrix:
  fast_finish: true